# Model arguments
# For definitions, see: src/h4/training/config.py
model_name_or_path: mistralai/Mistral-7B-v0.1
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: true

# Data training arguments
# For definitions, see: src/h4/training/config.py
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
block_size: 2048
dataset_mixer:
  HuggingFaceH4/ultrachat_200k: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12

# Training arguments with sensible defaults
# For definitions, see: src/h4/training/config.py
bf16: true
do_eval: true
do_train: true
evaluation_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: HuggingFaceH4/zephyr-7b-beta-ift
hub_private_repo: true
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: passive
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_steps: -1
num_train_epochs: 1
output_dir: data/zephyr-7b-beta-ift-v0.0
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 16
push_to_hub_revision: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
wandb_run_group: zephyr-7b-beta-ift
wandb_run_id: null
wandb_tags:
- ift
warmup_ratio: 0.1